#!/bin/bash

LIST=${1:-default}

if [ ! -d ${HOME}/.collections ]; then
	mkdir ${HOME}/.collections
fi

if [ "${LIST}" = "--list" ]; then
	ls ${HOME}/.collections
	exit 0
fi

if [ ! -f ${HOME}/.collections/${LIST} ]; then
	echo "List ${LIST} não existe."
	exit 1
fi

cat ${HOME}/.collections/$LIST
